ER図の追加
yojiyanase/runteq_graduation_examination pull request #5
Opened 2024-09-29 15:24 UTC by yojiyanase

2024-10-01 01:50 UTC, Tsuchiya2 commented
対応ありがとうございます。以下の点に関してコメントします。
回答及びER図への反映をお願いします。

---

ER図、README.mdを確認しました。
こちらのイメージしているものとの相違があるかもしれないため、新規コメント投稿に各テーブル・各カラムの役割や説明を記載してください。また、お手数ですがプルリクエストの概要のところにどんなサービスなのかも記載いただけると他の講師が見た際にもイメージしやすいため、対応をお願いいたします。

2024-10-01 14:59 UTC, yojiyanase commented
ありがとうございます。
サービス概要とテーブル・カラムの説明は以下のとおりです。
○サービス概要
ユーザーが、自分が持っているインデックスファンド（指数に連動する投資信託）の指数（S&P500など）と、毎月の積立金額（月１万円など）を選択して、過去の投資期間（1995年から1999年など）を指定すると、資産の変動がグラフで表示される（例えば、S&P５００を毎月１万円積み立てて、値動きが1990年から1995年の相場通りに動いた場合、資産の増減がどのようになるか表示する）。

○テーブル・カラムの説明
Search_Parametersテーブル（ユーザーが入力した内容を格納）
Investment_stockカラム(「積立指数」に入力した内容を格納)
Investment_amountカラム(「毎月積立額」に入力した内容を格納)
Investment_start_monthカラム(「仮想積立期間」の始期に入力した内容を格納)
Investment_end_monthカラム(「仮想積立期間」の終期に入力した内容を格納)

CSVsテーブル（Investing.comのサイトから取得したデータを格納）
product_nameカラム(商品（指数）名を格納)
reference_monthカラム(株価の基準月を格納)
priceカラム(株価の値を格納)

2024-10-03 02:02 UTC, Tsuchiya2 commented
対応ありがとうございます。
ER図レビューの前に、Investing.com のページを確認したところ、`Fusion Media およびデータ提供者による事前の書面の許可なしに、当ウェブサイト上のデータを使用、保存、複製、表示、変更、送信、配信することを禁じます。すべての知的財産権は当ウェブサイト上のデータの提供者、または取引所が有します。`とありますが、CSVsテーブルに格納するデータは大丈夫そうでしょうか。一度ご確認いただきたいです。

![image](https://github.com/user-attachments/assets/cf574641-5778-452c-a4c7-28665413980a)

2024-10-05 06:10 UTC, yojiyanase commented
ありがとうございます。
Investing.comに問い合わせし、下記のとおり了承を得たのでご報告します。
[Investing.comのCSVデータの利用について.pdf](https://github.com/user-attachments/files/17265306/Investing.com.CSV.pdf)

2024-10-06 03:40 UTC, tarakish requested changes
Investing.comのCSVデータの利用について、確認しました👍️
以下追加のコメントです！

---

- Search_Parameters
  - こちらDBに保存する必要性があるのか少し疑問に感じました。保存しておく理由があればご説明をいただきたいです。

- リレーション
  - CSVsとSearch_Parametersがリレーションとして繋げられていますが外部キーがなくどのように関連付けられるのかわかりませんでした。こちら見直していただけますか？

2024-10-06 06:32 UTC, yojiyanase commented
すみません、Search_Parametersについて不要であるため削除しました（「再計算する」ボタンを押した場合に前の検索内容が表示されるようにすることを視野に入れていましたが、MVPリリースではスコープに含まれないため削除します）。併せて、リレーションについても削除しました。
![ER図卒業試験](https://github.com/user-attachments/assets/5399a186-2937-4612-9e73-b34d3cbf9d2c)

2024-10-07 03:46 UTC, tmtkzk0823 commented
LGTMです。

追記：MVPは現状のテーブル数でいいですが、本リリース時はREADMEに記述している内容に加えて、テーブル数を増やす実装内容も考えておくといいかと思います。

2024-10-07 11:32 UTC, merged